
//cái này dât giả 
export const dataproducts = [
  {
    id: 1,
    title: 'Vietravel Airlines',
    time_start: '05:55',
    start: 'Hà Nội (HAN)',
    time_end: '8:10',
    end: 'TP HCM (SGN)',
    time: '2h15',
    style: 'Bay Thẳng',
    price: '150.000 VNĐ',
    cName: 'flight-text',
    isOpen: false
  },
  {
    id: 2,
    title: 'Vietravel Airlines',
    time_start: '05:55',
    start: 'Hà Nội (HAN)',
    time_end: '8:10',
    end: 'TP HCM (SGN)',
    time: '2h15',
    style: 'Bay Thẳng',
    price: '150.000 VNĐ',
    cName: 'flight-text',
    isOpen: false
  },
  {
    id: 3,
    title: 'Vietravel Airlines',
    time_start: '05:55',
    start: 'Hà Nội (HAN)',
    time_end: '8:10',
    end: 'TP HCM (SGN)',
    time: '2h15',
    style: 'Bay Thẳng',
    price: '150.000 VNĐ',
    cName: 'flight-text',
    isOpen: false
  },
  {
    id: 4,
    title: 'Vietravel Airlines',
    time_start: '05:55',
    start: 'Hà Nội (HAN)',
    time_end: '8:10',
    end: 'TP HCM (SGN)',
    time: '2h15',
    style: 'Bay Thẳng',
    price: '150.000 VNĐ',
    cName: 'flight-text',
    isOpen: false
  },
  {
    id: 5,
    title: 'Vietravel Airlines',
    time_start: '05:55',
    start: 'Hà Nội (HAN)',
    time_end: '8:10',
    end: 'TP HCM (SGN)',
    time: '2h15',
    style: 'Bay Thẳng',
    price: '130.000 VNĐ',
    cName: 'flight-text',
    isOpen: false
  },
  {
    id: 6,
    title: 'Vietravel Airlines',
    time_start: '05:55',
    start: 'Hà Nội (HAN)',
    time_end: '8:10',
    end: 'TP HCM (SGN)',
    time: '2h15',
    style: 'Bay Thẳng',
    price: '150.000 VNĐ',
    cName: 'flight-text',
    isOpen: false
  },
  {
    id: 7,
    title: 'Vietravel Airlines',
    time_start: '05:55',
    start: 'Hà Nội (HAN)',
    time_end: '8:10',
    end: 'TP HCM (SGN)',
    time: '2h15',
    style: 'Bay Thẳng',
    price: '150.000 VNĐ',
    cName: 'flight-text',
    isOpen: false
  },
  {
    id: 8,
    title: 'Vietravel Airlines',
    time_start: '05:55',
    start: 'Hà Nội (HAN)',
    time_end: '8:10',
    end: 'TP HCM (SGN)',
    time: '2h15',
    style: 'Bay Thẳng',
    price: '150.000 VNĐ',
    cName: 'flight-text',
    isOpen: false
  },
  {
    id: 9,
    title: 'Vietravel Airlines',
    time_start: '05:55',
    start: 'Hà Nội (HAN)',
    time_end: '8:10',
    end: 'TP HCM (SGN)',
    time: '2h15',
    style: 'Bay Thẳng',
    price: '150.000 VNĐ',
    cName: 'flight-text',
    isOpen: false
  },
  {
    id: 10,
    title: 'Vietravel Airlines',
    time_start: '05:55',
    start: 'Hà Nội (HAN)',
    time_end: '8:10',
    end: 'TP HCM (SGN)',
    time: '2h15',
    style: 'Bay Thẳng',
    price: '150.000 VNĐ',
    cName: 'flight-text',
    isOpen: false
  },
];